### PR TITLE
Updated to the new version of co-pg. 

### PR DESCRIPTION
**Pull request by timhaak**
Updated to the new version of co-pg. Upated to use new connectPromise. Added function for tagged template string. Updated examples on how to use.

### CODE REVIEW

**Comment by chilts** [comment]
Hi @timhaak - this looks awesome. I haven't tried it, but I'll presume it's all fine. Want me to release to npm?

**Comment by timhaak** [comment]
done some basic testing seems to work so should be good to go

**Comment by chilts** [comment]
Cool. Released yesterday as v0.24.0. :) Thanks for your help.

**Comment by chilts** [comment]
Just for your interest, v1.0.0 of koa-pg now just depends on "*" for co-pg so that the user is in control of which version to use. Basically this package is mostly a wrapper and doesn't depend on specific features, instead just passing them on.

**Pull request merged**
